### PR TITLE
chore(website-backend): bumped wordpress and plugin versions

### PR DESCRIPTION
**Pull request by manuelportela**
I tested locally (not thoroughly!):
- wordpress backend
- gatsby dev
- gatsby build

I'd think we should ship this to stage and ask our peeps to have a closer look as well.
Be aware that the database needs updates, which may cause problems on a downgrade. We should make sure to be able to roll back while going forward (at least by saving a point in time backup of the DB).

I ain't worried at all!

### CODE REVIEW

**Comment by manuelportela** [comment]
@phollome 
- prod db imported
- shipped to stage
- migrated to most recent wp core + plugins
- local build of gatsby was successful

I like ... you like?

**Comment by manuelportela** [comment]
@phollome fixed the remote peer version error issue by bumping the gatsby-source-wordpress dependency.
Sorry, obviously did build against prod which did not show the issue, because of an older remote wp plugin.
Action did go thru.

**Comment by manuelportela** [comment]
@phollome 

deployed to PROD Wordpress and successfully build locally against updated PROD.

In case of problems. The prior version DB is in reach on server in "~/deployments/_BACKUP"

**Review by phollome — APPROVED** [review]
👍

**Pull request merged**
